name: lint Markdown

on: [push]

jobs:
  lint-changelog:
    name: Lint README file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint README file
      uses: avto-dev/markdown-lint@v1
      with:
        config: '/.mdlrc'
        args: './README.md'
